// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
// Types are not available; using untyped client for now

const SUPABASE_URL = "https://dwyemauojftlyzzgujgh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR3eWVtYXVvamZ0bHl6emd1amdoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkzNjkyMDcsImV4cCI6MjA3NDk0NTIwN30.AYYJ3ikwLY1hnt1njt4S-gCliMTEJ_trUYkMri6MUas";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  global: {
    headers: {
      'x-app-module': 'tabungan',
      // Alias headers to accommodate backend variations
      'x-module': 'tabungan',
      'x-source-module': 'tabungan',
    }
  }
});